version: '3.8'

services:

  jupyter-api:
    build:
      context: .
      dockerfile: jupyter-api.Dockerfile
    volumes:
      - .:/workspaces/data-notebooks
    ports:
      - "9999:8888"
    command: /bin/bash -c "/workspaces/data-notebooks/startup-api.sh"
    environment:
      - SEED_URI=/workspaces/data-notebooks/notebooks/api/elevation.ipynb
    env_file:
      - .env
