# Basic settings file for the Geodata-Harvester w/o GEE.

# Path to the input file containing the site locations:
infile: input-data/test-location.csv

# Path to output directory (will be created if it doesn't exist):
outpath: output-data/

# Column names for latitude and longitude in input file:
colname_lat: Lat
colname_lng: Long

# Bounding box: Left (min Long), Bottom (min Lat), Right (max Long), Top (max Lat)
target_bbox: [116.26012130269045, -29.307384715430175, 116.3875862387774, -29.220237788279107]

# Resolution of data download in arcseconds (1 arcsec ~ 30m)
target_res: 3.0

# Start date and end date of image collection
date_min : 2023-10-01
date_max : 2023-11-30
# Number of time intervals to split the image collection into
time_intervals : 2

# List of data sources to download 
# see https://github.com/Sydney-Informatics-Hub/geodata-harvester#-data-sources
target_sources:
  SLGA:
    Bulk_Density: [0-5cm]
    Clay: [0-5cm]
